#############################################################################
# Makefile for building: libTapModel.so
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  TapModel.pro
# Template: app
# Command: /Users/user/V-PlaySDK/5.5/android_armv7/bin/qmake -spec android-g++ -o Makefile TapModel.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Users/user/Library/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
CXX           = /Users/user/Library/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_3DINPUT_LIB -DQT_3DRENDERER_LIB -DQT_3DQUICK_LIB -DQT_3DCORE_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -fno-builtin-memmove -Os -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -mthumb -Wall -Wno-psabi -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -fno-builtin-memmove -std=c++11 -O2 -Os -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -mthumb -Wall -Wno-psabi -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../V-PlaySDK/5.5/android_armv7/include/VPlay -I../../../V-PlaySDK/5.5/android_armv7/include -I../../../V-PlaySDK/5.5/android_armv7/include/QtQuick -I../../../V-PlaySDK/5.5/android_armv7/include/QtWidgets -I../../../V-PlaySDK/5.5/android_armv7/include/QtMultimedia -I../../../V-PlaySDK/5.5/android_armv7/include/Qt3DInput -I../../../V-PlaySDK/5.5/android_armv7/include/Qt3DRenderer -I../../../V-PlaySDK/5.5/android_armv7/include/Qt3DQuick -I../../../V-PlaySDK/5.5/android_armv7/include/Qt3DCore -I../../../V-PlaySDK/5.5/android_armv7/include/QtOpenGLExtensions -I../../../V-PlaySDK/5.5/android_armv7/include/QtGui -I../../../V-PlaySDK/5.5/android_armv7/include/QtQml -I../../../V-PlaySDK/5.5/android_armv7/include/QtWebSockets -I../../../V-PlaySDK/5.5/android_armv7/include/QtNetwork -I../../../V-PlaySDK/5.5/android_armv7/include/QtSql -I../../../V-PlaySDK/5.5/android_armv7/include/QtConcurrent -I../../../V-PlaySDK/5.5/android_armv7/include/QtCore -I. -I../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include -I../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -I../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include -I../../../V-PlaySDK/5.5/android_armv7/mkspecs/android-g++
QMAKE         = /Users/user/V-PlaySDK/5.5/android_armv7/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = libTapModel.so1.0.0
DISTDIR = /Users/user/Documents/VGames/TapModel/.tmp/libTapModel.so1.0.0
LINK          = /Users/user/Library/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=/Users/user/Library/android-ndk-r10e/platforms/android-9/arch-arm/ -Wl,-soname,libTapModel.so -Wl,-rpath=/Users/user/V-PlaySDK/5.5/android_armv7/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -L/Users/user/Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -L/Users/user/Library/android-ndk-r10e/platforms/android-9/arch-arm//usr/lib -L/Users/user/V-PlaySDK/5.5/android_armv7/lib -lVPlay -lQt5Quick -L/opt/android/ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -L/opt/android/ndk/platforms/android-9/arch-arm//usr/lib -lQt5Widgets -lQt5Multimedia -lQt53DInput -lQt53DRenderer -lQt53DQuick -lQt53DCore -lQt5OpenGLExtensions -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc -lQt5Gui -lQt5Qml -lQt5WebSockets -lQt5Network -lQt5Sql -lQt5Concurrent -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = /Users/user/Library/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = /Users/user/Library/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ranlib
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_resources.cpp \
		qrc_resources_user.cpp
OBJECTS       = main.o \
		qrc_resources.o \
		qrc_resources_user.o
DIST          = ../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/spec_pre.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/unix.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/linux.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/sanitize.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/gcc-base.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/gcc-base-unix.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/qdevice.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/device_config.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/qconfig.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcore.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dinput.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquick.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_androidextras.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_androidextras_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_concurrent.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_core.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_core_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_enginio.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_gui.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_gui_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_help.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_help_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_location.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_location_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimedia.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_network.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_network_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_nfc.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_opengl.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_positioning.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_printsupport.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qml.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qml_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmltest.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quick.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quick_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sensors.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sql.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sql_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_svg.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_svg_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_testlib.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uitools.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_webchannel.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_websockets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_widgets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xml.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xml_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt_functions.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt_config.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/android-g++/qmake.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/spec_post.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/exclusive_builds.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/default_pre.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/resolve_config.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/default_post.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/v-play.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/android/android.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/android/android_deployment_settings.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/warn_on.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/resources.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/moc.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/unix/opengl.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/uic.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/unix/thread.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/testcase_targets.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/exceptions.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/yacc.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/lex.prf \
		TapModel.pro  main.cpp
QMAKE_TARGET  = libTapModel.so
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libTapModel.so


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): /Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5OpenGLExtensions.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TapModel.pro ../../../V-PlaySDK/5.5/android_armv7/mkspecs/android-g++/qmake.conf ../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/spec_pre.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/unix.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/linux.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/sanitize.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/gcc-base.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/gcc-base-unix.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/qdevice.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/device_config.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/qconfig.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcore.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dinput.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquick.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_androidextras.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_androidextras_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_concurrent.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_core.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_core_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_enginio.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_gui.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_gui_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_help.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_help_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_location.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_location_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimedia.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_network.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_network_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_nfc.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_opengl.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_positioning.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_printsupport.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qml.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qml_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmltest.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quick.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quick_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sensors.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sql.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sql_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_svg.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_svg_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_testlib.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uitools.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_webchannel.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_websockets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_widgets.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xml.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xml_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt_functions.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt_config.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/android-g++/qmake.conf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/spec_post.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/exclusive_builds.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/default_pre.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/resolve_config.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/default_post.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/v-play.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/android/android.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/android/android_deployment_settings.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/warn_on.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/resources.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/moc.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/unix/opengl.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/uic.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/unix/thread.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/testcase_targets.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/exceptions.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/yacc.prf \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/lex.prf \
		TapModel.pro \
		resources.qrc \
		../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/vplay/resources_user.qrc \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Quick.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Widgets.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Multimedia.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DInput.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DRenderer.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DQuick.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DCore.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5OpenGLExtensions.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Gui.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Qml.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5WebSockets.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Network.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Sql.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Concurrent.prl \
		/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Core.prl
	$(QMAKE) -spec android-g++ -o Makefile TapModel.pro
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/spec_pre.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/unix.conf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/linux.conf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/sanitize.conf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/gcc-base.conf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/gcc-base-unix.conf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/qdevice.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/device_config.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/qconfig.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcollision.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcore.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dinput.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dlogic.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquick.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3drenderer.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_androidextras.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_androidextras_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bluetooth.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_clucene_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_concurrent.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_core.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_core_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_enginio.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_enginio_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_gui.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_gui_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_help.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_help_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_location.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_location_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimedia.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_network.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_network_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_nfc.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_nfc_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_opengl.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_opengl_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_openglextensions.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_positioning.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_positioning_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_printsupport.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qml.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qml_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmltest.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quick.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quick_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sensors.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sensors_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sql.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_sql_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_svg.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_svg_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_testlib.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_testlib_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uiplugin.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uitools.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_uitools_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_webchannel.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_websockets.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_websockets_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_widgets.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_widgets_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xml.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xml_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt_functions.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt_config.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/android-g++/qmake.conf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/spec_post.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/exclusive_builds.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/default_pre.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/resolve_config.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/default_post.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/v-play.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/android/android.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/android/android_deployment_settings.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/warn_on.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/qt.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/resources.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/moc.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/unix/opengl.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/uic.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/unix/thread.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/testcase_targets.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/exceptions.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/yacc.prf:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/features/lex.prf:
TapModel.pro:
resources.qrc:
../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/vplay/resources_user.qrc:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Quick.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Widgets.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Multimedia.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DInput.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DRenderer.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DQuick.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt53DCore.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5OpenGLExtensions.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Gui.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Qml.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5WebSockets.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Network.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Sql.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Concurrent.prl:
/Users/user/V-PlaySDK/5.5/android_armv7/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec android-g++ -o Makefile TapModel.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc ../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/vplay/resources_user.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp qrc_resources_user.cpp
qrc_resources.cpp: resources.qrc \
		qml/data/artifacts.json \
		qml/common/AudioManager.qml \
		qml/items/Player.qml \
		qml/common/AddonsData.qml \
		qml/common/Utils.js \
		qml/logic/DataLogic.js \
		qml/panels/StatsPanel.qml \
		qml/misc/KrkProgressBar.qml \
		qml/misc/KrkText.qml \
		qml/data/heroes.json \
		qml/logic/GameLogic.qml \
		qml/misc/WaitScreen.qml \
		qml/items/ClothBox.qml \
		qml/logic/JSONListModel.qml \
		qml/config.json \
		qml/misc/CollectionDialog.qml \
		qml/items/Coin.qml \
		qml/misc/KrkDialog.qml \
		qml/items/Cloth.qml \
		qml/logic/JsonPath.js \
		qml/misc/KrkTextButton.qml \
		qml/common/ItemsMetadata.qml \
		qml/data/skills.json \
		qml/panels/KrkPanel.qml \
		qml/panels/MainPanel.qml \
		qml/MainItem.qml \
		qml/scenes/MenuScene.qml \
		qml/common/SkillsData.qml \
		qml/Main.qml \
		qml/misc/KrkTimer.qml \
		qml/misc/GameOverScreen.qml \
		qml/data/data.json \
		qml/scenes/ItemScene.qml \
		qml/common/KrkStorage.qml \
		qml/panels/ArtifactsPanel.qml \
		qml/panels/SkillsPanel.qml \
		qml/scenes/CollectionScene.qml \
		qml/common/CollectionsMetadata.qml \
		qml/panels/HeroesPanel.qml \
		qml/scenes/SplashScene.qml \
		qml/scenes/CollectionsScene.qml \
		qml/common/HeroesData.qml \
		qml/items/Boundary.qml \
		qml/misc/KrkButton.qml \
		qml/particles/stars.json \
		qml/common/ArtifactsData.qml \
		qml/scenes/GameScene.qml \
		qml/scenes/KrkScene.qml \
		qml/misc/KrkText.qml \
		qml/misc/KrkTimer.qml \
		qml/misc/WaitScreen.qml \
		qml/misc/KrkTextButton.qml \
		qml/misc/KrkButton.qml \
		qml/misc/KrkProgressBar.qml \
		qml/misc/GameOverScreen.qml \
		qml/misc/CollectionDialog.qml \
		qml/misc/KrkDialog.qml \
		qml/data/heroes.json \
		qml/data/skills.json \
		qml/data/data.json \
		qml/data/artifacts.json \
		qml/logic/DataLogic.js \
		qml/logic/JSONListModel.qml \
		qml/logic/JsonPath.js \
		qml/logic/GameLogic.qml \
		qml/items/Boundary.qml \
		qml/items/Coin.qml \
		qml/items/Player.qml \
		qml/items/ClothBox.qml \
		qml/items/Cloth.qml \
		qml/scenes/SplashScene.qml \
		qml/scenes/CollectionScene.qml \
		qml/scenes/MenuScene.qml \
		qml/scenes/GameScene.qml \
		qml/scenes/KrkScene.qml \
		qml/scenes/CollectionsScene.qml \
		qml/scenes/ItemScene.qml \
		qml/common/AddonsData.qml \
		qml/common/ArtifactsData.qml \
		qml/common/AudioManager.qml \
		qml/common/CollectionsMetadata.qml \
		qml/common/Utils.js \
		qml/common/HeroesData.qml \
		qml/common/SkillsData.qml \
		qml/common/ItemsMetadata.qml \
		qml/common/KrkStorage.qml \
		qml/panels/StatsPanel.qml \
		qml/panels/SkillsPanel.qml \
		qml/panels/ArtifactsPanel.qml \
		qml/panels/HeroesPanel.qml \
		qml/panels/KrkPanel.qml \
		qml/panels/MainPanel.qml
	/Users/user/V-PlaySDK/5.5/android_armv7/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

qrc_resources_user.cpp: ../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/vplay/resources_user.qrc \
		../../../V-PlaySDK/V-Play/vplay_license.key
	/Users/user/V-PlaySDK/5.5/android_armv7/bin/rcc -name resources_user ../../../V-PlaySDK/5.5/android_armv7/mkspecs/common/vplay/resources_user.qrc -o qrc_resources_user.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp ../../../V-PlaySDK/5.5/android_armv7/include/QtWidgets/QApplication \
		../../../V-PlaySDK/5.5/android_armv7/include/QtWidgets/qapplication.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qcoreapplication.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qglobal.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cstddef \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/c++config.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/os_defines.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/cpu_defines.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qconfig.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qfeatures.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qsystemdetection.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qprocessordetection.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qcompilerdetection.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/utility \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_relops.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_pair.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/move.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/concept_check.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/boost_concept_check.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_iterator_base_types.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/type_traits \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/c++0x_warning.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cstdint \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/stdint.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/_types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/machine/_types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/android/api-level.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/initializer_list \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/algorithm \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algobase.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/functexcept.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/exception_defines.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/cpp_type_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/type_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/numeric_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_iterator_base_funcs.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/debug.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/macros.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/functions.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_function.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward/binders.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/formatter.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/typeinfo \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/exception \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_lockfree_defines.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/exception_ptr.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/nested_exception.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/hash_bytes.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/ptr_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/predefined_ops.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/algobase.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/features.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/basic_iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/parallel.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/compiletime_settings.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cstdio \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/stdio.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/types.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cstdlib \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/stdlib.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/string.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/malloc.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/alloca.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/strings.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/memory.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/limits \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/cstdint \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/tags.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/settings.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/algorithmfwd.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/find.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/compatibility.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sched.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/time.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/time.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/equally_split.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/find_selectors.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_algo.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/algorithmfwd.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_heap.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_tempbuf.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_construct.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/new \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/alloc_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/alloc_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/memoryfwd.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/allocator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/c++allocator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/new_allocator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/random \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cmath \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/math.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/limits.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/limits.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/limits.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/machine/internal_types.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/machine/limits.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/syslimits.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/page.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/string \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stringfwd.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/char_traits.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/wchar.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/time.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/siginfo.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm-generic/siginfo.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/localefwd.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/c++locale.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/clocale \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/locale.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/iosfwd \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cctype \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/ctype.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/ostream_insert.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/cxxabi_forced.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/range_access.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/gthr.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/gthr-default.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/pthread.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/signal.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/signal.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm-generic/signal.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/sigcontext.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/ucontext.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/user.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/unistd.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/select.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/sys/sysconf.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/capability.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/pathconf.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/atomic_word.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/string_conversions.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cerrno \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/errno.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/linux/errno.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm/errno.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm-generic/errno.h \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/asm-generic/errno-base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/functional_hash.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/random.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/vector \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_uninitialized.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_vector.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_bvector.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/vector.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/vector \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_sequence.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/concurrence.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_sequence.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_iterator.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/vector \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/functional \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tuple \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/array \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/stdexcept \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/array \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/array \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/uses_allocator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_hash_func.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_node.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_trace.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/unordered_map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/aligned_buffer.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/hashtable.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/hashtable_policy.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/unordered_map.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/unordered_map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_unordered_container.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_unordered_base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_unordered_container.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_local_iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/safe_local_iterator.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/unordered_map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/unordered_base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/unordered_map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/type_traits \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/functional_hash.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/hashtable.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/hashtable_policy.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/unordered_map.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/fstream \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/istream \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ios \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/ios_base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/locale_classes.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/locale_classes.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/streambuf.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_ios.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/locale_facets.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cwctype \
		../../../Library/android-ndk-r10e/platforms/android-9/arch-arm/usr/include/wctype.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/ctype_base.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/streambuf_iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/ctype_inline.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/locale_facets.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_ios.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/ostream \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/ostream.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/istream.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/codecvt.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/basic_file.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/c++io.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/fstream.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_algos.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_state.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_hashtable_size.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_container_size.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/sstream.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_map_to_unordered_map.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_vector_size.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_vector_to_list.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_list_to_slist.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/impl/profiler_list_to_vector.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/iterator_tracker.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/bits/opt_random.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/random.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/numeric \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_numeric.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/numeric \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/numericfwd.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/for_each.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/par_loop.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/omp_loop.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/workstealing.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/random_number.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/random \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/cmath \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/gamma.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/special_function_util.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/bessel_function.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/beta_function.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/ell_integral.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/exp_integral.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/hypergeometric.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/legendre_function.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/modified_bessel_func.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/poly_hermite.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/poly_laguerre.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/riemann_zeta.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/random.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/random.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/for_each_selectors.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/partial_sum.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/algorithm \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/algo.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/sort.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/checkers.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/multiway_mergesort.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/multiway_merge.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/losertree.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/multiseq_selection.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/queue \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/deque \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_deque.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/deque.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/deque \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/deque \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_queue.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/quicksort.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/partition.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/balanced_quicksort.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/queue.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/omp_loop_static.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/search.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/random_shuffle.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/merge.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/unique_copy.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/parallel/set_operations.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qtypeinfo.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qtypetraits.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qsysinfo.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qlogging.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qflags.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qbasicatomic.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_bootstrap.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qgenericatomic.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_cxx11.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/atomic \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_gcc.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_msvc.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_armv7.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_armv6.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_armv5.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_ia64.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_mips.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_x86.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qatomic_unix.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qglobalstatic.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qmutex.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qnumeric.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qstring.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qchar.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qbytearray.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qrefcount.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qnamespace.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qarraydata.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qstringbuilder.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qobject.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qobjectdefs.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qobjectdefs_impl.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qlist.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qalgorithms.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qiterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/iterator \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stream_iterator.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/list \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_list.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/list.tcc \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/list \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/list \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qbytearraylist.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qstringlist.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qregexp.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qstringmatcher.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qcoreevent.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qscopedpointer.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qmetatype.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qvarlengtharray.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qcontainerfwd.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qisenum.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_tree.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_map.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/stl_multimap.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/map.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/debug/multimap.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/map \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/map.h \
		../../../Library/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/profile/multimap.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qobject_impl.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qeventloop.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qwindowdefs.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qwindowdefs_win.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qpoint.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qsize.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qcursor.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtWidgets/qdesktopwidget.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtWidgets/qwidget.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qmargins.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qpaintdevice.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qrect.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qpalette.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qcolor.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qrgb.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qbrush.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qpair.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qvector.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qmatrix.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qpolygon.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qregion.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qdatastream.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qiodevice.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qline.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qtransform.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qpainterpath.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qimage.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qpixelformat.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qpixmap.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qsharedpointer.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qshareddata.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qhash.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qsharedpointer_impl.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qfont.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qfontmetrics.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qfontinfo.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtWidgets/qsizepolicy.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qkeysequence.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qevent.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qvariant.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qmap.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qdebug.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qtextstream.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qlocale.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qset.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qcontiguouscache.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qurl.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qurlquery.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qfile.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qfiledevice.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qvector2d.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qtouchdevice.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qguiapplication.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtGui/qinputmethod.h \
		../../../V-PlaySDK/5.5/android_armv7/include/VPlay/VPApplication \
		../../../V-PlaySDK/5.5/android_armv7/include/VPlay/vpapplication.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/QObject \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/QAbstractAnimation \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/qabstractanimation.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/QStringList \
		../../../V-PlaySDK/5.5/android_armv7/include/QtCore/QVariantMap \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/QQmlApplicationEngine \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qqmlapplicationengine.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qqmlengine.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qjsengine.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qjsvalue.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qtqmlglobal.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qqmlerror.h \
		../../../V-PlaySDK/5.5/android_armv7/include/QtQml/qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

qrc_resources_user.o: qrc_resources_user.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources_user.o qrc_resources_user.cpp

####### Install

install_itemqmlFolder: first FORCE
	@test -d $(INSTALL_ROOT)/assets/ || mkdir -p $(INSTALL_ROOT)/assets/
	-$(INSTALL_DIR) /Users/user/Documents/VGames/TapModel/qml $(INSTALL_ROOT)/assets/

uninstall_itemqmlFolder: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/assets/qml
	-$(DEL_DIR) $(INSTALL_ROOT)/assets/ 


install_itemassetsFolder: first FORCE
	@test -d $(INSTALL_ROOT)/assets/ || mkdir -p $(INSTALL_ROOT)/assets/
	-$(INSTALL_DIR) /Users/user/Documents/VGames/TapModel/assets $(INSTALL_ROOT)/assets/

uninstall_itemassetsFolder: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/assets/assets
	-$(DEL_DIR) $(INSTALL_ROOT)/assets/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/libs/armeabi-v7a/ || mkdir -p $(INSTALL_ROOT)/libs/armeabi-v7a/
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/libs/armeabi-v7a/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/libs/armeabi-v7a/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/libs/armeabi-v7a/ 


install: install_itemqmlFolder install_itemassetsFolder install_target  FORCE

uninstall: uninstall_itemqmlFolder uninstall_itemassetsFolder uninstall_target  FORCE

FORCE:

